jregex-1.2_01/pom.xml
jregex-1.2_01/src/main/resources/OSGI-INF/bundle.info

Add JRegex to the list of bundles that ServiceMix has available to projects.

Add JRegex 1.2_01 to servicemix bundles.

---

aws-java-sdk-1.10.27/pom.xml
aws-java-sdk-1.10.27/src/main/resources/OSGI-INF/bundle.info

Hi,
https://issues.apache.org/jira/browse/SM-2702
Andrea

[SM-2702] Create OSGi bundle for aws-java-sdk 1.10.27

---

aws-java-sdk-1.10.28/pom.xml
aws-java-sdk-1.10.28/src/main/resources/OSGI-INF/bundle.info
pom.xml

Hi,
https://issues.apache.org/jira/browse/SM-2708
Andrea

[SM-2708] Create OSGi bundle for aws-java-sdk 1.10.28

---

aws-java-sdk-1.10.29/pom.xml
aws-java-sdk-1.10.29/src/main/resources/OSGI-INF/bundle.info
pom.xml

Hi,
https://issues.apache.org/jira/browse/SM-2712
Andrea

[SM-2712] Create OSGi bundle for aws-java-sdk 1.10.29

---

elasticsearch-1.7.3/pom.xml
elasticsearch-1.7.3/src/main/resources/OSGI-INF/bundle.info
pom.xml

Hi all,
https://issues.apache.org/jira/browse/SM-2711
Andrea

[SM-2711] Create OSGi bundle for Elasticsearch 1.7.3

---

mustache-compiler-0.8.18/pom.xml
mustache-compiler-0.8.18/src/main/resources/OSGI-INF/bundle.info
pom.xml

Hi,
https://issues.apache.org/jira/browse/SM-2705
Thanks,
Andrea

[SM-2705] Create OSGi bundle for Mustache compiler 0.8.18

---

mustache-compiler-0.9.1/pom.xml
mustache-compiler-0.9.1/src/main/resources/OSGI-INF/bundle.info
pom.xml

Hi,
https://issues.apache.org/jira/browse/SM-2704
Andrea

[SM-2704] Create OSGi bundle for Mustache compiler 0.9.1

---

libthrift-0.9.3/pom.xml
libthrift-0.9.3/src/main/resources/OSGI-INF/bundle.info
pom.xml

Hi,
https://issues.apache.org/jira/browse/SM-2703
Andrea

[SM-2703] Create OSGi bundle for Libthrift 0.9.3

---

aws-java-sdk-1.10.31/pom.xml
aws-java-sdk-1.10.31/src/main/resources/OSGI-INF/bundle.info
pom.xml

Hi all,
https://issues.apache.org/jira/browse/SM-2723
Andrea

[SM-2723] Create OSGi bundle for aws-java-sdk 1.10.31

---

aws-java-sdk-1.10.32/pom.xml
aws-java-sdk-1.10.32/src/main/resources/OSGI-INF/bundle.info
pom.xml

Hi all,
https://issues.apache.org/jira/browse/SM-2724
Andrea

[SM-2724] Create OSGi bundle for aws-java-sdk 1.10.32

---

aws-java-sdk-1.10.33/pom.xml
aws-java-sdk-1.10.33/src/main/resources/OSGI-INF/bundle.info
pom.xml

Hi all,
https://issues.apache.org/jira/browse/SM-2725
Andrea

[SM-2725] Create OSGi bundle for aws-java-sdk 1.10.33

---

ognl-3.1.1/pom.xml
ognl-3.1.1/src/main/resources/OSGI-INF/bundle.info
pom.xml

Hi all,
https://issues.apache.org/jira/browse/SM-2726
Andrea

[SM-2726] Create OSGi bundle for Ognl 3.1.1

---

elasticsearch-2.0.0/pom.xml
elasticsearch-2.0.0/src/main/resources/OSGI-INF/bundle.info
pom.xml

Hi all,
https://issues.apache.org/jira/browse/SM-2730
Andrea

[SM-2730] Create OSGi bundle for Elasticsearch 2.0.0

---

olingo-odata2-api-2.0.5/pom.xml
olingo-odata2-api-2.0.5/src/main/resources/OSGI-INF/bundle.info
olingo-odata2-core-2.0.5/pom.xml
olingo-odata2-core-2.0.5/src/main/resources/OSGI-INF/bundle.info
pom.xml

Hi all,
https://issues.apache.org/jira/browse/SM-2731
Andrea

[SM-2731] Create OSGi bundle for Olingo 2.0.5

---

aws-java-sdk-1.10.34/pom.xml
aws-java-sdk-1.10.34/src/main/resources/OSGI-INF/bundle.info
pom.xml

Hi all,
https://issues.apache.org/jira/browse/SM-2735
Andrea

[SM-2735] Create OSGi bundle for aws-java-sdk 1.10.34

---

gae-1.9.28/pom.xml
gae-1.9.28/src/main/resources/OSGI-INF/bundle.info
pom.xml

Hi all,
https://issues.apache.org/jira/browse/SM-2736
Andrea

[SM-2736] Create OSGi bundle for GAE 1.9.28

---

aws-java-sdk-1.10.35/pom.xml
aws-java-sdk-1.10.35/src/main/resources/OSGI-INF/bundle.info
pom.xml

Hi all,
https://issues.apache.org/jira/browse/SM-2740
Andrea

[SM-2740] Create OSGi bundle for aws-java-sdk 1.10.35

---

aws-java-sdk-1.10.30/pom.xml
aws-java-sdk-1.10.30/src/main/resources/OSGI-INF/bundle.info
pom.xml

Hi,
https://issues.apache.org/jira/browse/SM-2721
Andrea

[SM-2721] Create OSGi bundle for aws-java-sdk 1.10.30

---

kafka-clients-0.9.0.0/pom.xml
kafka-clients-0.9.0.0/src/main/resources/OSGI-INF/bundle.info
kafka_2.10-0.9.0.0/pom.xml
kafka_2.10-0.9.0.0/src/main/resources/OSGI-INF/bundle.info
pom.xml

Hi all,
This PR is related:
https://issues.apache.org/jira/browse/SM-2743
Andrea

[SM-2743] Create OSGi bundles for Kafka 0.9.0.0

---

facebook4j-2.4.0/pom.xml
facebook4j-2.4.0/src/main/resources/OSGI-INF/bundle.info
pom.xml

Hi all,
https://issues.apache.org/jira/browse/SM-2755
Andrea

[SM-2755] Create OSGi bundle for Facebook4j 2.4.0

---

facebook4j-2.4.1/pom.xml
facebook4j-2.4.1/src/main/resources/OSGI-INF/bundle.info
pom.xml

Hi all,
https://issues.apache.org/jira/browse/SM-2756
Andrea

[SM-2756] Create OSGi bundle for Facebook4j 2.4.1

---

docker-java-2.1.2/pom.xml
docker-java-2.1.2/src/main/resources/OSGI-INF/bundle.info
pom.xml

Hi all,
https://issues.apache.org/jira/browse/SM-2757
Andrea

[SM-2757] Create OSGi bundle for docker-java 2.1.2

---

aws-java-sdk-1.10.38/pom.xml
aws-java-sdk-1.10.38/src/main/resources/OSGI-INF/bundle.info
pom.xml

Hi all,
https://issues.apache.org/jira/browse/SM-2758
Andrea

[SM-2758] Create OSGi bundle for aws-java-sdk 1.10.38

---

aws-java-sdk-1.10.39/pom.xml
aws-java-sdk-1.10.39/src/main/resources/OSGI-INF/bundle.info
pom.xml

Hi all,
https://issues.apache.org/jira/browse/SM-2760
Andrea

[SM-2760] Create OSGi bundle for aws-java-sdk 1.10.39

---

elasticsearch-2.0.1/pom.xml
elasticsearch-2.0.1/src/main/resources/OSGI-INF/bundle.info
pom.xml

Hi all,
https://issues.apache.org/jira/browse/SM-2761
Andrea

[SM-2761] Create OSGi bundle for Elasticsearch 2.0.1

---

gae-1.9.30/pom.xml
gae-1.9.30/src/main/resources/OSGI-INF/bundle.info
pom.xml

Hi all,
https://issues.apache.org/jira/browse/SM-2762
Andrea

[SM-2762] Create OSGi bundle for GAE 1.9.30

---

aws-java-sdk-1.10.40/pom.xml
aws-java-sdk-1.10.40/src/main/resources/OSGI-INF/bundle.info
pom.xml

Hi all,
https://issues.apache.org/jira/browse/SM-2765
Andrea

[SM-2765] Create OSGi bundle for aws-java-sdk 1.10.40

---

docker-java-2.1.3/pom.xml
docker-java-2.1.3/src/main/resources/OSGI-INF/bundle.info
pom.xml

Hi all,
https://issues.apache.org/jira/browse/SM-2766
Andrea

[SM-2766] Create OSGi bundle for docker-java 2.1.3

---

aws-java-sdk-1.10.41/pom.xml
aws-java-sdk-1.10.41/src/main/resources/OSGI-INF/bundle.info
pom.xml

Hi all,
https://issues.apache.org/jira/browse/SM-2771
Andrea

[SM-2771] Create OSGi bundle for aws-java-sdk 1.10.41

---

pom.xml
quickfix-1.6.1/pom.xml
quickfix-1.6.1/src/main/resources/OSGI-INF/bundle.info

Related to https://issues.apache.org/jira/browse/SM-2773

[SM-2773] Create OSGi bundle for QuickFIX/J 1.6.1

---

lucene-5.4.0/pom.xml
lucene-5.4.0/src/main/resources/OSGI-INF/bundle.info
lucene-analyzers-common-5.4.0/pom.xml
lucene-analyzers-common-5.4.0/src/main/resources/OSGI-INF/bundle.info
lucene-queries-5.4.0/pom.xml
lucene-queries-5.4.0/src/main/resources/OSGI-INF/bundle.info
lucene-queryparser-5.4.0/pom.xml
lucene-queryparser-5.4.0/src/main/resources/OSGI-INF/bundle.info
lucene-sandbox-5.4.0/pom.xml
lucene-sandbox-5.4.0/src/main/resources/OSGI-INF/bundle.info
pom.xml

Hi all,
https://issues.apache.org/jira/browse/SM-2774
Andrea

[SM-2774] Create OSGi bundles for Lucene 5.4.0

---

pom.xml
solr-solrj-5.4.0/pom.xml
solr-solrj-5.4.0/src/main/resources/OSGI-INF/bundle.info

Hi all,
https://issues.apache.org/jira/browse/SM-2775
Andrea

[SM-2775] Create OSGi bundle for Solr 5.4.0

---

braintree-java-2.53.0/pom.xml
braintree-java-2.53.0/src/main/resources/OSGI-INF/bundle.info
pom.xml

Linked to https://issues.apache.org/jira/browse/SM-2776

[SM-2776] Create OSGi bundle for Braintree Java SDK 2.53.0

---

poi-3.13/pom.xml

export all packages within org.apache.poi*
add missing ooxml-security
export additional missing package

fix missing exports

---

chunk-templates-3.1.3/pom.xml
chunk-templates-3.1.3/src/main/resources/OSGI-INF/bundle.info
pom.xml

Hi all,
https://issues.apache.org/jira/browse/SM-2788
Andrea

[SM-2788] Create OSGi bundle for Chunk-templates 3.1.3

---

aws-java-sdk-1.10.42/pom.xml
aws-java-sdk-1.10.42/src/main/resources/OSGI-INF/bundle.info
pom.xml

Hi all,
https://issues.apache.org/jira/browse/SM-2781
Andrea

[SM-2781] Create OSGi bundle for aws-java-sdk 1.10.42

---

elasticsearch-2.0.2/pom.xml
elasticsearch-2.0.2/src/main/resources/OSGI-INF/bundle.info
pom.xml

Hi all,
https://issues.apache.org/jira/browse/SM-2783
Andrea

[SM-2783] Create OSGi bundle for Elasticsearch 2.0.2

---

elasticsearch-2.1.1/pom.xml
elasticsearch-2.1.1/src/main/resources/OSGI-INF/bundle.info
pom.xml

Hi all,
https://issues.apache.org/jira/browse/SM-2784
Andrea

[SM-2784] Create OSGi bundle for Elasticsearch 2.1.1

---

facebook4j-2.4.2/pom.xml
facebook4j-2.4.2/src/main/resources/OSGI-INF/bundle.info
pom.xml

Hi all,
https://issues.apache.org/jira/browse/SM-2811
Andrea

[SM-2811] Create OSGi bundle for Facebook4j 2.4.2

---

bazaarvoice-jolt-0.0.20/pom.xml
bazaarvoice-jolt-0.0.20/src/main/resources/OSGI-INF/bundle.info
pom.xml

Hi all,
https://issues.apache.org/jira/browse/SM-2812
Andrea

[SM-2812] Create OSGi bundle for jolt 0.0.20

---

java_nats-0.5.2/pom.xml
java_nats-0.5.2/src/main/resources/OSGI-INF/bundle.info
pom.xml

Hi all,
https://issues.apache.org/jira/browse/SM-2815
Andrea

[SM-2815] Create OSGi bundle for java_nats 0.5.2

---

spring-jdbc-3.2.16.RELEASE/pom.xml
spring-webmvc-3.2.16.RELEASE/pom.xml

Sync spring-jdbc and spring-webmvc to _1-SNAPSHOT
Sorry, missed setting the patchlevel to _1 for all submodules.

[SM-2817] Create OSGi bundles for Spring 3.2.16.RELEASE

---

chunk-templates-3.2.0/pom.xml
chunk-templates-3.2.0/src/main/resources/OSGI-INF/bundle.info
pom.xml

Hi all,
https://issues.apache.org/jira/browse/SM-2870
Andrea

[SM-2870] Create OSGi bundle for Chunk-templates 3.2.0

---

cglib-3.2.1/pom.xml
cglib-3.2.1/src/main/resources/OSGI-INF/bundle.info
pom.xml

Hi all,
https://issues.apache.org/jira/browse/SM-2884
Thanks,
Andrea

[SM-2884] Create OSGi bundle for Cglib 3.2.1

---

lucene-5.5.0/pom.xml
lucene-5.5.0/src/main/resources/OSGI-INF/bundle.info
lucene-analyzers-common-5.5.0/pom.xml
lucene-analyzers-common-5.5.0/src/main/resources/OSGI-INF/bundle.info
lucene-queries-5.5.0/pom.xml
lucene-queries-5.5.0/src/main/resources/OSGI-INF/bundle.info
lucene-queryparser-5.5.0/pom.xml
lucene-queryparser-5.5.0/src/main/resources/OSGI-INF/bundle.info
lucene-sandbox-5.5.0/pom.xml
lucene-sandbox-5.5.0/src/main/resources/OSGI-INF/bundle.info
pom.xml

Hi all,
https://issues.apache.org/jira/browse/SM-2888
Andrea

[SM-2888] Create OSGi bundles for Lucene 5.5.0

---

pom.xml
solr-solrj-5.5.0/pom.xml
solr-solrj-5.5.0/src/main/resources/OSGI-INF/bundle.info

Hi all,
https://issues.apache.org/jira/browse/SM-2889
Andrea

[SM-2889] Create OSGi bundle for Solr 5.5.0

---

jedis-2.8.0/pom.xml
jedis-2.8.0/src/main/resources/OSGI-INF/bundle.info
pom.xml

Hi all,
https://issues.apache.org/jira/browse/SM-2894
Thanks,
Andrea

[SM-2894] Create OSGi bundle for Jedis 2.8.0

---

pom.xml
swagger-jaxrs-1.3.10/src/main/scala/com/wordnik/swagger/jaxrs/listing/ApiListing.scala
swagger-jaxrs-1.3.11/src/main/scala/com/wordnik/swagger/jaxrs/listing/ApiListing.scala
swagger-jaxrs-1.3.12/src/main/scala/com/wordnik/swagger/jaxrs/listing/ApiListing.scala
swagger-jaxrs-1.3.13/src/main/scala/com/wordnik/swagger/jaxrs/listing/ApiListing.scala
swagger-jaxrs-1.3.2/src/main/scala/com/wordnik/swagger/jaxrs/listing/ApiListing.scala
swagger-jaxrs-1.3.4/src/main/scala/com/wordnik/swagger/jaxrs/listing/ApiListing.scala
swagger-jaxrs-1.3.5/src/main/scala/com/wordnik/swagger/jaxrs/listing/ApiListing.scala
swagger-jaxrs-1.3.7/src/main/scala/com/wordnik/swagger/jaxrs/listing/ApiListing.scala
swagger-jaxrs-1.3.8/src/main/scala/com/wordnik/swagger/jaxrs/listing/ApiListing.scala
swagger-jaxrs_2.11-1.3.12/src/main/scala/com/wordnik/swagger/jaxrs/listing/ApiListing.scala

https://issues.apache.org/jira/browse/SM-3342
Please merge this. Thanks!

[SM-3342] swagger-jaxrs may throw NPE when non-default HTTP port is used with CXF

---

hadoop-client-2.7.7/pom.xml
hadoop-client-2.7.7/src/main/resources/OSGI-INF/bundle.info
pom.xml

https://issues.apache.org/jira/browse/SM-4100
Thanks!

[SM-4100] Create hadoop-client 2.7.7 bundle

---

any23-2.3/pom.xml
any23-2.3/src/main/resources/OSGI-INF/bundle.info

Hi , I'm a student of GSoC, currently I'm collaborating with the apache camel project. I need include this bundle for this task. Because, I'm working on karaf platform support for apache any23. Please , give it a look. 
thanks, Roberto.

Creation any23 bundle

---

poi-5.2.2/pom.xml

Package META-INF/services files
Exclude log4j API

Fix POI-5.2.2

---

opensaml-4.3.2/pom.xml

Fixes [SM-5826](https://issues.apache.org/jira/browse/SM-5826).

SM-5826: Fix version range
