apache/servicemix-bundles

- xalan-2.7.2/src/main/java/org/apache/xalan/processor/XSLTElementProcessor.java
This fix is based on Mike Lyons' patch at [XALANJ-2591](https://issues.apache.org/jira/browse/XALANJ-2591) but removed the fallback system property that disables secure processing completely.
> SM-2880 - Fix XALANJ-2591 Transform XSLT using Xalan into XHTML fails with secure processing feature when using attributes

- pom.xml
- spring-security-acl-4.1.0.RELEASE/pom.xml
- spring-security-acl-4.1.0.RELEASE/src/main/resources/OSGI-INF/bundle.info
- spring-security-config-4.1.0.RELEASE/pom.xml
- spring-security-config-4.1.0.RELEASE/src/main/resources/OSGI-INF/bundle.info
- spring-security-core-4.1.0.RELEASE/pom.xml
- spring-security-core-4.1.0.RELEASE/src/main/resources/OSGI-INF/bundle.info
- spring-security-taglibs-4.1.0.RELEASE/pom.xml
- spring-security-taglibs-4.1.0.RELEASE/src/main/resources/OSGI-INF/bundle.info
- spring-security-web-4.1.0.RELEASE/pom.xml
- spring-security-web-4.1.0.RELEASE/src/main/resources/OSGI-INF/bundle.info
This PR includes ServiceMix bundles for:
- spring-security-acl-4.1.0.RELEASE
- spring-security-config-4.1.0.RELEASE
- spring-security-core-4.1.0.RELEASE
- spring-security-taglibs-4.1.0.RELEASE
- spring-security-web-4.1.0.RELEASE
> SM-2982 : Create OSGi bundles for Spring Security 4.1.0

- jest-0.1.6/pom.xml
Dependency on org.apache.httpcomponents/httpasyncclient-osgi incorrectly reference version 4.4 of packages exported by it
> Jest bundle has wrong dependency on httpasyncclient-osgi 4.1 packages

- spring-security-config-5.1.2.RELEASE/pom.xml
The Web and LDAP imports for Spring Security are not mandatory.
> Marked optional imports for Spring Security as such

- aws-java-sdk-s3-1.11.496/pom.xml
- aws-java-sdk-s3-1.11.496/src/main/resources/OSGI-INF/bundle.info
- pom.xml
@jbonofre 
Can we follow a path like this one and releasing the aws-sdk-java-core as a separated bundle? In this way we can split camel-aws in multiple components and install only what we need.
> [SM-3964] Create OSGi bundle for aws-java-sdk-s3 1.11.496

- poi-4.0.1/pom.xml
- xmlbeans-3.0.2/pom.xml
During POI's *.xsb parsing xmlbeans can't find base schemas because of using POI's classloader. That's causing exception's like below. xmlbeans bundle should export common schemas.
`Caused by: org.apache.xmlbeans.SchemaTypeLoaderException: Cannot resolve type for handle _XY_Q=space|R=space@http://www.w3.org/XML/1998/namespace (schemaorg_apache_xmlbeans.system.sD023D6490046BA0250A839A9AD24C443.cttext7f5btype) - code 13
at org.apache.xmlbeans.impl.schema.SchemaTypeSystemImpl$XsbReader.readHandle(SchemaTypeSystemImpl.java:2025)
at org.apache.xmlbeans.impl.schema.SchemaTypeSystemImpl$XsbReader.readTypeRef(SchemaTypeSystemImpl.java:2099)
at org.apache.xmlbeans.impl.schema.SchemaTypeSystemImpl$XsbReader.loadAttribute(SchemaTypeSystemImpl.java:2926)
at …
> Using POI without base xmlbeans schemas not working

- casbah-3.1.1/pom.xml
- gentlyweb-utils-1.5/pom.xml
- hapi-0.5.1/pom.xml
- hsqldb-1.8.0.10/pom.xml
- jain-sip-ri-1.2.169/pom.xml
- javassist-3.12.1.GA/pom.xml
- jsmpp-2.1.0/pom.xml
- neo4j-3.5.12/pom.xml
- netty-3.2.10.Final/pom.xml
- orbitz-consul-client-1.3.3/pom.xml
- restlet-1.1.10/pom.xml
- rome-1.0/pom.xml
- scalaj-collection-1.0/pom.xml
- smack-3.2.1/pom.xml
- splunk-1.6.5.0/pom.xml
[![mitm_build](https://user-images.githubusercontent.com/1323708/59226671-90645200-8ba1-11e9-8ab3-39292bef99e9.jpeg)](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Update: Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/bugbountywriteup/update-want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-d069d253fe23?source=friends_link&sk=8c8e52a7d57b98d0b7e541665688b454)
---
This is a security fix for …
> [SECURITY] Use HTTPS to resolve dependencies in Maven Build

- elasticsearch-client-6.1.1/pom.xml
This tweaks the configuration in order for the camel-elasticsearch-rest
to be able to work (in version 2.2x).
> camel-elasticsearch-rest dependencies

- spring-oxm-5.2.8.RELEASE/pom.xml
XStreamMarshaller uses the class SingletonSupplier from org.springframework.util.function [here](https://github.com/spring-projects/spring-framework/blob/v5.2.8.RELEASE/spring-oxm/src/main/java/org/springframework/oxm/xstream/XStreamMarshaller.java#L87).
> XStreamMarshaller broken because of missing package import

- spring-ws-support-2.4.2.RELEASE/pom.xml
- spring-ws-support-3.0.9.RELEASE/pom.xml
This bundle adds extra classes to spring-ws-core and exports some of the
same packages. It should attach to that bundle and complement it.
If deployed as it currently is, it will result in use constraint
violations for importing bundles since packages like
org.springframework.ws.transport will resolve via two dependency chains.
The last upstream version with OSGi metadata also packaged this bundle
as a fragment.
https://repo1.maven.org/maven2/org/springframework/ws/spring-ws-support/2.1.4.RELEASE/spring-ws-support-2.1.4.RELEASE.jar
> spring-ws-support should be a fragment bundle.

- poi-4.1.2/pom.xml
POI requires Batik for SVG support. Reference: https://poi.apache.org/components/index.html#components
It also uses `javax.imageio` packages, so I added an import for those
> Add missing imports: javax.imageio.* and org.apache.batik.*

- spring-security-oauth2-client-5.3.3.RELEASE/pom.xml
- spring-security-oauth2-core-5.3.3.RELEASE/pom.xml
- spring-security-oauth2-jose-5.3.3.RELEASE/pom.xml
Hello,
I tested spring-security oauth2 in a osgi blueprint/spring application configured using spring security dsl <http> like described in Example 94 https://docs.spring.io/spring-security/site/docs/current/reference/html5/#oauth2login-advanced.
I needed to fix various bundle metadata, and jose jar was missing packages.
Here the pull request with my fixes.
> fix spring-security oauth2 bundles

- castor-1.4.1/pom.xml
The current castor bundle surprises me with the following exception: `java.lang.ClassNotFoundException: org.apache.commons.lang3.StringUtils cannot be found by org.apache.servicemix.bundles.castor_1.4.1.1` at `AbstractProperties.java` line 661. This is due to a missing package import of `org.apache.commons.lang3`. Here's a fix.
> Fix castor-1.4.1 package imports

- spring-jdbc-5.2.9.RELEASE/pom.xml
SQLErrorCodeSQLExceptionTranslator uses the classes SingletonSupplier and SupplierUtils from this package [here](https://github.com/spring-projects/spring-framework/blob/v5.2.9.RELEASE/spring-jdbc/src/main/java/org/springframework/jdbc/support/SQLErrorCodeSQLExceptionTranslator.java#L38).
> SQLErrorCodeSQLExceptionTranslator broken because of missing package import

- spring-context-5.3.0/pom.xml
This package is referenced by [AbstractApplicationContext](https://github.com/spring-projects/spring-framework/blob/v5.3.0/spring-context/src/main/java/org/springframework/context/support/AbstractApplicationContext.java#L81) among others.
> Add missing metrics package import to spring-context-5.3.0.

- spring-security-oauth2-jose-5.4.1/pom.xml
Switching to latest spring security, we were facing a ClassNotFoundException for com.nimbusds.jose.RemoteKeySourceException
This PR is a proposed fix for that issue.
> fix spring-security oauth2-jose

- pulsar-client-2.7.0/pom.xml
The servicemix for pulsar client is failing to initialize because of missing import of new compression library.
> pulsar-client - add io.airlift.compress as import

- spring-ws-core-3.0.10.RELEASE/pom.xml
Using org.springframework.ws.transport.jms.WebServiceMessageListener
with an AxiomSoapMessageFactory will result in a
java.lang.NoClassDefFoundError.
```
2021-02-02 16:06:28,022 [ws-jms-1] WARN  org.springframework.jms.listener.DefaultMessageListenerContainer - Execution of JMS message listener failed, and no ErrorHandler has been set.
java.lang.NoClassDefFoundError: org/apache/axiom/mime/MediaType
at org.springframework.ws.soap.axiom.AxiomSoapMessageFactory.createWebServiceMessage(AxiomSoapMessageFactory.java:235)
at org.springframework.ws.soap.axiom.AxiomSoapMessageFactory.createWebServiceMessage(AxiomSoapMessageFactory.java:85)
at org.springframework.ws.transport.AbstractWebServiceConnection.receive(AbstractWebServiceConnection.java:92)
at …
```
> Add missing org.apache.axiom.mime import to spring-ws-core.

- spring-ldap-2.3.3.RELEASE/pom.xml
org.springframework.LdapDataEntry is part of public spring ldap api, so spring-ldap should export org.springframework package otherwise it could lead to some access restriction
> fix spring-ldap missing export

- spring-batch-infrastructure-4.3.2/pom.xml
The StaxEvent classes in spring-batch require StaxUtils which is in this
package.
Example:
https://github.com/spring-projects/spring-batch/blob/4.3.2/spring-batch-infrastructure/src/main/java/org/springframework/batch/item/xml/StaxEventItemReader.java#L48
```
Caused by: java.lang.ClassNotFoundException: org.springframework.util.xml.StaxUtils not found by org.apache.servicemix.bundles.spring-batch-infrastructure [90]
at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1597)
at org.apache.felix.framework.BundleWiringImpl.access$300(BundleWiringImpl.java:79)
at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1982)
at java.lang.ClassLoader.loadClass(ClassLoader.java:413)
... 518 common frames …
```
> Add missing spring util.xml import to spring-batch-infrastructure.

- spring-security-core-5.5.0/pom.xml
I noticed spring-security-core import kotlinx packages as mandatory. It seems wrong to me, these dependences needs to be set as optional
> set kotlinx dependences as optional

- spring-oxm-5.3.13/pom.xml
Spring OXM's XStreamMarshaller references this package here:
https://github.com/spring-projects/spring-framework/blob/v5.3.13/spring-oxm/src/main/java/org/springframework/oxm/xstream/XStreamMarshaller.java#L66
```
Caused by: java.lang.ClassNotFoundException: com.thoughtworks.xstream.security.TypePermission not found by org.apache.servicemix.bundles.spring-oxm [99]
at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1597)
at org.apache.felix.framework.BundleWiringImpl.access$300(BundleWiringImpl.java:79)
at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1982)
at java.lang.ClassLoader.loadClass(ClassLoader.java:413)
... 71 common frames omitted
```
> Add missing dependency on com.thoughtworks.xstream.security to spring-oxm.

- okhttp-4.10.0/pom.xml
As `okio-jvm` exports version 3.0.0.
> Fix OkHttp 4.10.0 bundle import

- kafka-streams-3.4.0/pom.xml
kafka-streams logs an exception at startup because a properties file is missing:
```
org.apache.kafka.streams.internals.metrics.ClientMetrics <clinit> WARN: Error while loading kafka-streams-version.properties
java.lang.NullPointerException: inStream parameter is null
at java.base/java.util.Objects.requireNonNull(Objects.java:233)
at java.base/java.util.Properties.load(Properties.java:407)
at org.apache.kafka.streams.internals.metrics.ClientMetrics.<clinit>(ClientMetrics.java:53)
at org.apache.kafka.streams.KafkaStreams.<init>(KafkaStreams.java:894)
at org.apache.kafka.streams.KafkaStreams.<init>(KafkaStreams.java:856)
at org.apache.kafka.streams.KafkaStreams.<init>(KafkaStreams.java:826)
at org.apache.kafka.streams.KafkaStreams.<init>(KafkaStreams.java:738)
```
> Fix kafka-streams 3.4.0 bundle

- solr-solrj-9.1.1/pom.xml
Solr import org.eclipse.jetty
```
$ java -jar biz.aQute.bnd-6.3.1.jar xref --to --destination 'org.eclipse.jetty*' ~/.m2/repository/org/apache/solr/solr-solrj/9.1.1/solr-solrj-9.1.1.jar
org.apache.solr.client.solrj.embedded > org.eclipse.jetty.util.ssl
org.apache.solr.client.solrj.impl > org.eclipse.jetty.client.util
org.eclipse.jetty.client.api
org.eclipse.jetty.http
org.eclipse.jetty.util.ssl
org.eclipse.jetty.util
org.eclipse.jetty.client.http
org.eclipse.jetty.http2.client.http
org.eclipse.jetty.http2.client
org.eclipse.jetty.client
org.apache.solr.client.solrj.util > org.eclipse.jetty.util
org.eclipse.jetty.http
org.eclipse.jetty.client.api
```
> Fix solrj 9.1.1 bundle import

- spring-security-acl-5.8.5/pom.xml
- spring-security-acl-6.0.5/pom.xml
- spring-security-acl-6.1.2/pom.xml
`spring-security-acl` needs packages `org.springframework.core.convert.converter` and `org.springframework.core.convert.support`.
> Fix package import for spring-security-acl

- spring-jms-6.1.5/pom.xml
Fixes https://issues.apache.org/jira/browse/SM-5706
NoClassDefFoundErrors are raised when we use the SMX bundle of Spring JMS because Micrometer is not part of its import packages
* Add the packages of micrometer that are used by spring-jms to the import packages
> [SM-5706] Add micrometer to spring-jms

- spring-security-web-6.1.9/pom.xml
- spring-security-web-6.2.7/pom.xml
- spring-security-web-6.3.9/pom.xml
- spring-security-web-6.4.5/pom.xml
I am starting to use the Spring Security 6 bundles and found the webauthn4j package imports are required, but can be optional. This change is to mark those packages as optional in the Spring Security 6 bundles.
> Make webauthn4j optional in Spring Security 6 web.

- spring-core-6.0.23/pom.xml
- spring-core-6.1.19/pom.xml
- spring-core-6.2.6/pom.xml
Spring Core 6 uses classes in the `reactor.adapter` package but that is not imported. This PR adds that import to the Spring Core 6 bundles.
> Add missing reactor.adapter package import to Spring Core 6 bundles
